# Generated by Django 5.2 on 2025-04-09 15:01

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_bio_alter_user_cidade_alter_user_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="perfil",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.upload_foto_perfil
            ),
        ),
    ]
